### ISSUE TITLE
HTML::Form 6.06 breaks WWW::Mechanize 1.95

### ISSUE THREAD

**Issue by eserte** [libwww-perl/HTML-Form#22]
If the newest HTML::Form is installed, then WWW::Mechanize's test suite fails:
```
Invalid index 0 at /usr/perl5.30.0p/lib/site_perl/5.30.0/HTML/Form.pm line 511.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 3.
t/tick.t ................................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 3 subtests passed 
```
Might be related to https://github.com/libwww-perl/HTML-Form/issues/19 .

**Comment by eserte** [comment]
My pet project is also affected: https://travis-ci.org/eserte/bbbike/jobs/653162473#L3314-L3316

**Comment by oalders** [comment]
@eserte will the referenced PR fix `bbbike`? (Nice project!)

**Comment by eserte** [comment]
Yes: installed WWW::Mechanize from github (https://travis-ci.org/eserte/bbbike/jobs/653202520#L1217) and it's green.

**Comment by oalders** [comment]
@eserte I've released a new `WWW::Mechanize`.  Thanks for reporting this.
