### ISSUE TITLE
Tidy this dist

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTML-Form#25]
Now would be a good time to tidy this dist.

**Comment by simbabque** [comment]
What do you mean by _tidy_?

**Comment by oalders** [comment]
I meant basically to apply `perltidy`, but I wanted to do that after all outstanding pull requests were taken care of, but I see we still have https://github.com/libwww-perl/HTML-Form/issues/6 and https://github.com/libwww-perl/HTML-Form/issues/10, so I will close this for now.
