### ISSUE TITLE
Adding pod as requested in Bug #87689

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTML-Form#4]
<a href="https://github.com/lancew"><img src="https://avatars2.githubusercontent.com/u/11627?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lancew](https://github.com/lancew)**
_Friday Jan 09, 2015 at 23:04 GMT_
_Originally opened as https://github.com/gisle/html-form/pull/4_

----

----

_**[lancew](https://github.com/lancew)** included the following code: https://github.com/gisle/html-form/pull/4/commits_

**Comment by simbabque** [comment]
This includes a working PR that looks good.

**Comment by oalders** [comment]
@simbabque do you have a moment to turn this into a PR against this repository?

**Comment by simbabque** [comment]
Turns out it had some issues with your dzil tests. The second one includes my fix.
