### ISSUE TITLE
make ->attr() work for action

### ISSUE THREAD

**Issue by oalders** [libwww-perl/HTML-Form#6]
<a href="https://github.com/fany"><img src="https://avatars2.githubusercontent.com/u/343083?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fany](https://github.com/fany)**
_Friday Sep 09, 2016 at 20:53 GMT_
_Originally opened as https://github.com/gisle/html-form/pull/6_

----

The `->attr()` method did not work for the `action` attribute, because that one got `delete`d in `->parse()`.
I would like it to work for my [new `->form_with()` method in WWW::Mechanize](https://github.com/fany/WWW-Mechanize/commit/bff39f3143eb12e601c57efeeb2fa8d74a368ac5).

----

_**[fany](https://github.com/fany)** included the following code: https://github.com/gisle/html-form/pull/6/commits_

**Comment by simbabque** [comment]
The `delete` was put in in 2001 in https://github.com/gisle/html-form/commit/47b30f76568a8e6b7766ad742a494f1a9341899e. That commit looks like the near opposite of the one being proposed here. While I don't see anything wrong with the proposed change from only reading the code, I am reluctant about it given it's been explicitly done the last time that particular piece of code was touched. I don't understand the reason Gisle had to do this though.

**Comment by oalders** [comment]
Thanks for looking into this @simbabque.  I think what might be going on here is that since `action` is being captured in `$self->{action}` allowing it remain part of the tag attribute means having to track the value in two places.  So, in order for this change to be consistent, the `action` method should *probably* use the `form` tag's action attribute rather than keeping another copy.

This may also get complicated by the fact that `action` is also a parameter to `new()`.

**Comment by simbabque** [comment]
I have proposed an alternative solution in WWW::Mechanize that does not make this change. Given no other dependency of HTML::Form has asked for this, I think we'd better not change the existing behaviour. Instead, Mech can do this very easily by filtering on action explicitly.
